#! /usr/bin/env python

if __name__ == "__main__":
    import importlib
    import sys
    import re
    sslh_cli    = importlib.import_module("sslh-cli")
    main        = sslh_cli.__main__.main
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
