import sys
import spikeinterface.full as si

prmsdict = {}
desrdict = {}
for srt in si.available_sorters():
    prmsdict[srt] = si.get_default_sorter_params(srt)
    desrdict[srt] = si.get_sorter_params_description(srt)

def getlist(prms:dict, desr:dict ):
    ret = ""
    nprms = len([     _  for _ in prms ])-1
    width = max([ len(_) for _ in prms ])+1 
    for xi,x in enumerate(prms):
        ret += f'        "{x}"'+(',' if xi != nprms else '')+' '*(width-len(x))+f'\t# {desr[x] if x in desr else None}\n'
    return ret

sorting_senity="SORTING_SANITY = {\n"
for srt in prmsdict:
    sorting_senity += f'    "{srt}" : [\n'
    sorting_senity += getlist(prmsdict[srt],desrdict[srt])
    sorting_senity += '     ],\n'
sorting_senity += '}'

with open('../runthepipe/__sorting_sanity.py','w') as fd:
    fd.write(f"""'''
    WARNING! This file is automatically generated by generators/{sys.argv[0]}
    Any changes of this file will be lost on the next clone/update
'''\n\n""")
    fd.write(f'SI_VERSION="{si.__version__}"\n\n')
    fd.write(sorting_senity+'\n')
